### ISSUE TITLE
Error while retrieving data

### ISSUE THREAD

**Issue by HadeeqaKaramat** [e-Contract/eid-idp-nodejs#1]
Hello,

I have tried using your demo but when i log in with my pin on e-contract.com, there is an error message. 
Is there error caused by me or by the web site ?

Thank you.
![screenshot 19](https://user-images.githubusercontent.com/25612763/36966545-5c5667ec-205d-11e8-902a-b144200cb4b5.png)

**Comment by HadeeqaKaramat** [comment]
Problem : there was no given name thus the error

**Comment by fcorneli** [comment]
Will be fixed within the next version of eID Identity Provider.
